### ISSUE TITLE
stuck at loading machine

### ISSUE THREAD

**Issue by summerock** [ybootin/mamejs#1]
hi, i'm trying to get the demo to work with sf2 for cps1. I already obtain the mame.js and everything,  but when i go and run the demo directory, i'm stuck at "loading machine" message.

I checked the google console it it say 

stderr:
Array(9)
0:"buf1 NOT FOUND (tried in sf2 sf2)"
1:"ioa1 NOT FOUND (tried in sf2 sf2)"
2:"prg1 NOT FOUND (tried in sf2 sf2)"
3:"rom1 NOT FOUND (tried in sf2 sf2)"
4:"sou1 NOT FOUND (tried in sf2 sf2)"
5:"stf29.1a NOT FOUND (tried in sf2 sf2)"
6:"iob1.11d NOT FOUND (tried in sf2 sf2)"
7:"c632.ic1 NOT FOUND (tried in sf2 sf2)"
8:"Required files are missing, the machine cannot be run."

Any clue? Thanks

**Comment by ybootin** [comment]
Hi

i don't provide the roms on github.

Look at this file : 
https://github.com/ybootin/mamejs/blob/master/demo/gamelist.json

the sf2.zip rom must be placed in the `roms/` directory. 
Also the roms have to merged to works.

On my side SF2 works great.

**Comment by summerock** [comment]
Hi thanks for the reply. 

I believe i did put the rom inside the roms/ directory. 

I run the following commend ./mame-compiler.sh cps1 to get the mame.js

Here is a link to the demo http://104.131.85.107/mamejs-master3/demo/ as you can see the game doesn't load. Do you have any idea? 

Thanks.

**Comment by ybootin** [comment]
The problem is the rom you are using. I think the version of the SF2 rom you use is not fully merge. And the emulator needs fully merged roms, because it load them at once, and can't find missing roms in clones or others dump (like mame do on your local file system)

you can find a working sf2 rom here : 
https://uploadfiles.io/ac29r

Just replace your rom with this one.

**Comment by summerock** [comment]
You are right. After i replaced it with your fully merged version it works. 

Are you getting the same error message i'm getting after running Marvel Super Hero? 

`abort("Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 268435456, (2) compile with -s ALLOW_MEMORY_GROWTH=1 which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with -s ABORTING_MALLOC=0 ") at Error at jsStackTrace (http://104.131.85.107/mamejs-master3/dist/mame.js:1:3010052) at stackTrace (http://104.131.85.107/mamejs-master3/dist/mame.js:1:3010235) at abort (http://104.131.85.107/mamejs-master3/dist/mame.js:24:12062) at abortOnCannotGrowMemory (http://104.131.85.107/mamejs-master3/dist/mame.js:1:3011028) at enlargeMemory (http://104.131.85.107/mamejs-master3/dist/mame.js:1:3011473) at Function.dynamicAlloc [as alloc] (http://104.131.85.107/mamejs-master3/dist/mame.js:1:2999945) at _sbrk (http://104.131.85.107/mamejs-master3/dist/mame.js:1:9975808) at WOd (http://104.131.85.107/mamejs-master3/dist/mame.js:16:842912) at A_d (http://104.131.85.107/mamejs-master3/dist/mame.js:17:68568) at y1 (http://104.131.85.107/mamejs-master3/dist/mame.js:7:706509) If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information. `

You can see what i mean on http://104.131.85.107/mamejs-master3/demo/

I made sure to have the correct rom and even correct qsound.zip and tested it on the local installed mame machine using those two files it works. 

Do you have any idea why? Thanks a lot.

**Comment by summerock** [comment]
Hi, i would like to talk to you about freelance work for your mamejs, please contact 32113222@mail.com if your interested.

**Comment by C-Windows-System32-cmd** [comment]
> The problem is the rom you are using. I think the version of the SF2 rom you use is not fully merge. And the emulator needs fully merged roms, because it load them at once, and can't find missing roms in clones or others dump (like mame do on your local file system)
> 
> you can find a working sf2 rom here : https://uploadfiles.io/ac29r
> 
> Just replace your rom with this one.

Dead link (410)
